// Code generated by MockGen. DO NOT EDIT.
// Source: signaling.go
//
// Generated by this command:
//
//	mockgen -source=signaling.go -destination=signalingmock/repository.go -package=signalingmock
//

// Package signalingmock is a generated GoMock package.
package signalingmock

import (
	context "context"
	reflect "reflect"
	time "time"

	signaling "github.com/pj-hoakari/tolo-signaling/internal/signaling"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CreateSession mocks base method.
func (m *MockRepository) CreateSession(ctx context.Context, edgeID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSession", ctx, edgeID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSession indicates an expected call of CreateSession.
func (mr *MockRepositoryMockRecorder) CreateSession(ctx, edgeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSession", reflect.TypeOf((*MockRepository)(nil).CreateSession), ctx, edgeID)
}

// EdgeExists mocks base method.
func (m *MockRepository) EdgeExists(ctx context.Context, edgeID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EdgeExists", ctx, edgeID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EdgeExists indicates an expected call of EdgeExists.
func (mr *MockRepositoryMockRecorder) EdgeExists(ctx, edgeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EdgeExists", reflect.TypeOf((*MockRepository)(nil).EdgeExists), ctx, edgeID)
}

// ListAliveEdges mocks base method.
func (m *MockRepository) ListAliveEdges(ctx context.Context, cutoff time.Time) ([]signaling.Edge, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAliveEdges", ctx, cutoff)
	ret0, _ := ret[0].([]signaling.Edge)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAliveEdges indicates an expected call of ListAliveEdges.
func (mr *MockRepositoryMockRecorder) ListAliveEdges(ctx, cutoff any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAliveEdges", reflect.TypeOf((*MockRepository)(nil).ListAliveEdges), ctx, cutoff)
}
